export const newConditions = [
  {
    slug: "rectal-prolapse",
    title: "Rectal Prolapse",
    altTitle: "Prolapsed Rectum",
    shortDesc: "When the rectum slides out of place — expert surgical correction available.",
    icon: "ArrowDownCircle",
    seoTitle: "Rectal Prolapse Treatment in Palanpur | Dr. Parth Prajapati",
    seoDesc: "Expert rectal prolapse treatment in Palanpur. Dr. Parth Prajapati offers advanced surgical correction with fast recovery.",
    heroHeadline: "Rectal Prolapse Treatment in Palanpur",
    definition: "Rectal prolapse occurs when part or all of the wall of the rectum slides out of place, sometimes protruding through the anus. It can range from a mild internal prolapse to a full-thickness external prolapse. While it can affect anyone, it is more common in older adults and women. Early treatment prevents complications and improves quality of life significantly.",
    causes: [
      { label: "Chronic Constipation", desc: "Long-term straining weakens pelvic floor muscles and rectal support" },
      { label: "Weakened Pelvic Floor", desc: "Age-related or post-childbirth weakening of pelvic support structures" },
      { label: "Chronic Diarrhea", desc: "Repeated loose stools can weaken rectal tissue over time" },
      { label: "Previous Surgery", desc: "Prior pelvic or rectal surgery can increase prolapse risk" },
      { label: "Neurological Conditions", desc: "Spinal cord injuries or conditions affecting nerve supply to the rectum" },
      { label: "Aging", desc: "Natural weakening of muscles and ligaments with advancing age" },
    ],
    symptoms: [
      { label: "Protruding Tissue", desc: "Visible reddish tissue bulging from the anus, especially during bowel movements" },
      { label: "Fecal Incontinence", desc: "Difficulty controlling bowel movements or mucus leakage" },
      { label: "Incomplete Evacuation", desc: "Feeling of not fully emptying the bowel after a movement" },
      { label: "Rectal Bleeding", desc: "Mild bleeding from the exposed or irritated rectal tissue" },
      { label: "Discomfort & Pain", desc: "Aching or dragging sensation in the lower abdomen or rectum" },
    ],
    conservative: [
      "Pelvic floor exercises (Kegel exercises) to strengthen muscles",
      "High-fiber diet with adequate hydration to prevent straining",
      "Stool softeners to ease bowel movements",
      "Biofeedback therapy for pelvic floor retraining",
      "Avoiding heavy lifting and prolonged straining",
    ],
    surgical: [
      { procedure: "Laparoscopic Rectopexy", desc: "Keyhole surgery to secure the rectum in its correct position", advantages: "Minimally invasive, faster recovery, less pain", disadvantages: "Requires general anesthesia, specialized equipment" },
      { procedure: "Delorme's Procedure", desc: "Removal of the inner lining of the prolapsed rectum", advantages: "Suitable for elderly, can be done under regional anesthesia", disadvantages: "Higher recurrence rate than abdominal approaches" },
      { procedure: "Altemeier's Procedure", desc: "Perineal approach to remove the prolapsed segment", advantages: "No abdominal incision, suitable for high-risk patients", disadvantages: "Potential for recurrence, may affect continence" },
    ],
    aftercare: [
      "Maintain a high-fiber diet and stay well hydrated",
      "Continue pelvic floor exercises as recommended",
      "Avoid heavy lifting for 4–6 weeks post-surgery",
      "Use stool softeners to prevent straining",
      "Attend all follow-up appointments for monitoring",
      "Report any signs of recurrence promptly",
    ],
    faqs: [
      { q: "What is rectal prolapse?", a: "Rectal prolapse is a condition where the rectum (the last part of the large intestine) slides out of its normal position and protrudes through the anus." },
      { q: "What causes rectal prolapse?", a: "Common causes include chronic constipation, weakened pelvic floor muscles, aging, previous surgeries, and neurological conditions." },
      { q: "Is rectal prolapse dangerous?", a: "While not immediately life-threatening, untreated prolapse can worsen over time, leading to incontinence, ulceration, and significant quality of life issues." },
      { q: "Can rectal prolapse be treated without surgery?", a: "Mild cases may improve with pelvic floor exercises and dietary changes, but most cases require surgical correction for lasting relief." },
      { q: "What is the recovery time?", a: "Recovery varies by procedure — laparoscopic surgery typically requires 2–4 weeks, while perineal procedures may heal faster." },
      { q: "Can rectal prolapse recur after surgery?", a: "Recurrence is possible but rates are low with modern surgical techniques (5–10%). Pelvic floor exercises reduce recurrence risk." },
    ],
  },
  {
    slug: "anal-papilla",
    title: "Anal Papilla",
    altTitle: "Hypertrophied Anal Papilla",
    shortDesc: "Enlarged papillae in the anal canal causing discomfort — treatable with minor surgery.",
    icon: "CircleDot",
    seoTitle: "Anal Papilla Treatment in Palanpur | Dr. Parth Prajapati",
    seoDesc: "Expert anal papilla treatment in Palanpur by Dr. Parth Prajapati. Quick, minimally invasive removal with fast recovery.",
    heroHeadline: "Anal Papilla Treatment in Palanpur",
    definition: "Anal papillae are small, finger-like projections located at the dentate line inside the anal canal. When these become enlarged or hypertrophied, they can cause symptoms like pain, itching, and a sensation of incomplete evacuation. Often mistaken for polyps or hemorrhoids, they are benign growths that can be easily treated.",
    causes: [
      { label: "Chronic Inflammation", desc: "Ongoing irritation from fissures, hemorrhoids, or infections causes papillae to enlarge" },
      { label: "Anal Fissures", desc: "Sentinel piles from chronic fissures can stimulate papilla growth" },
      { label: "Chronic Diarrhea", desc: "Repeated irritation from loose stools triggers inflammatory enlargement" },
      { label: "Poor Hygiene", desc: "Inadequate anal hygiene can contribute to chronic irritation" },
      { label: "Hemorrhoids", desc: "Associated hemorrhoidal disease can cause papillary hypertrophy" },
    ],
    symptoms: [
      { label: "Sensation of Lump", desc: "Feeling of a mass or foreign body inside the anal canal" },
      { label: "Incomplete Evacuation", desc: "Persistent feeling of not fully emptying the bowel" },
      { label: "Anal Itching", desc: "Pruritus ani or persistent itching around the anal area" },
      { label: "Mild Pain", desc: "Discomfort or mild pain during and after bowel movements" },
      { label: "Mucus Discharge", desc: "Slight mucus discharge from the anus" },
    ],
    conservative: [
      "High-fiber diet to maintain soft, regular stools",
      "Proper anal hygiene with gentle cleansing",
      "Sitz baths for symptom relief",
      "Topical anti-inflammatory medications",
      "Treatment of underlying conditions (fissures, hemorrhoids)",
    ],
    surgical: [
      { procedure: "Papillectomy", desc: "Simple excision of the enlarged papilla under local anesthesia", advantages: "Quick procedure, immediate relief, minimal downtime", disadvantages: "Minor bleeding risk, rare recurrence" },
      { procedure: "Electrocautery Removal", desc: "Removal using electrical current to cut and cauterize simultaneously", advantages: "Minimal bleeding, precise removal", disadvantages: "Mild post-operative discomfort" },
      { procedure: "Laser Removal", desc: "Precise laser excision of hypertrophied papillae", advantages: "Minimal pain, fast healing, reduced infection risk", disadvantages: "Higher cost than conventional methods" },
    ],
    aftercare: [
      "Keep the area clean and dry after the procedure",
      "Use sitz baths 2–3 times daily for the first week",
      "Take prescribed pain medications as needed",
      "Maintain a high-fiber diet to prevent constipation",
      "Avoid strenuous activity for 1–2 weeks",
      "Follow up as scheduled for wound assessment",
    ],
    faqs: [
      { q: "What is an anal papilla?", a: "Anal papillae are small projections at the dentate line in the anal canal. When they become enlarged (hypertrophied), they can cause symptoms." },
      { q: "Are anal papillae cancerous?", a: "No. Hypertrophied anal papillae are benign (non-cancerous) growths. However, proper diagnosis is important to rule out other conditions." },
      { q: "How are anal papillae diagnosed?", a: "They are diagnosed through a proctoscopic examination where the doctor visualizes the inside of the anal canal." },
      { q: "Is surgery necessary?", a: "Surgery is recommended when papillae cause significant symptoms. Small, asymptomatic papillae may only need monitoring." },
      { q: "What is the recovery time?", a: "Most patients recover within 1–2 weeks after papillectomy with minimal discomfort." },
    ],
  },
  {
    slug: "perianal-abscess",
    title: "Perianal Abscess",
    altTitle: "Anorectal Abscess",
    shortDesc: "Painful collection of pus near the anus — requires drainage and expert treatment.",
    icon: "ShieldAlert",
    seoTitle: "Perianal Abscess Treatment in Palanpur | Dr. Parth Prajapati",
    seoDesc: "Expert perianal abscess drainage and treatment in Palanpur by Dr. Parth Prajapati. Same-day relief with advanced care.",
    heroHeadline: "Perianal Abscess Treatment in Palanpur",
    definition: "A perianal abscess is a painful, pus-filled cavity that develops near the anus or rectum. It typically results from an infection of the small glands inside the anal canal. If left untreated, a perianal abscess can lead to serious complications including fistula formation. Prompt drainage and appropriate antibiotic therapy are essential.",
    causes: [
      { label: "Infected Anal Glands", desc: "Blockage and infection of the small glands lining the anal canal" },
      { label: "Anal Fissures", desc: "Tears in the anal lining can become infected and form abscesses" },
      { label: "Inflammatory Bowel Disease", desc: "Crohn's disease and ulcerative colitis increase abscess risk" },
      { label: "Diabetes", desc: "Impaired immunity in diabetic patients increases infection susceptibility" },
      { label: "Weakened Immunity", desc: "Conditions or medications that suppress the immune system" },
      { label: "Trauma", desc: "Injury to the anal area from surgery, foreign bodies, or other causes" },
    ],
    symptoms: [
      { label: "Severe Pain", desc: "Intense, constant throbbing pain near the anus that worsens with sitting" },
      { label: "Swelling & Redness", desc: "Visible swelling, redness, and warmth around the anal area" },
      { label: "Fever & Chills", desc: "Systemic signs of infection including high fever and malaise" },
      { label: "Pus Drainage", desc: "Spontaneous drainage of foul-smelling pus if the abscess ruptures" },
      { label: "Difficulty Sitting", desc: "Extreme discomfort when sitting or during bowel movements" },
    ],
    conservative: [
      "Antibiotics for early-stage or mild infections",
      "Warm compresses and sitz baths for symptom relief",
      "Pain management with prescribed analgesics",
      "Monitoring for signs of progression",
    ],
    surgical: [
      { procedure: "Incision & Drainage", desc: "Surgical opening and draining of the abscess cavity", advantages: "Immediate relief, can be done under local anesthesia", disadvantages: "Wound requires packing and daily care" },
      { procedure: "Drainage with Fistula Assessment", desc: "Drainage combined with examination for underlying fistula tract", advantages: "Addresses both abscess and potential fistula simultaneously", disadvantages: "May require staged procedures" },
      { procedure: "Catheter Drainage", desc: "Placement of a small catheter for continuous drainage", advantages: "Lower recurrence rate, controlled drainage", disadvantages: "Catheter needs to stay in place for several days" },
    ],
    aftercare: [
      "Keep the wound clean with regular sitz baths",
      "Change wound packing/dressing as instructed",
      "Complete the full course of prescribed antibiotics",
      "Take pain medications as needed",
      "Watch for signs of fistula formation (persistent drainage)",
      "Follow up within 1–2 weeks for wound assessment",
    ],
    faqs: [
      { q: "What is a perianal abscess?", a: "It is a painful collection of pus that forms near the anus, usually from an infected anal gland." },
      { q: "Can an abscess heal on its own?", a: "Rarely. Most abscesses require surgical drainage. Delaying treatment can lead to serious complications including fistula." },
      { q: "How quickly do I need treatment?", a: "Perianal abscesses are considered urgent. Seek medical attention promptly to prevent the infection from spreading." },
      { q: "Will I develop a fistula?", a: "About 30–50% of perianal abscesses may lead to fistula formation. Early and proper treatment reduces this risk." },
      { q: "What is the recovery time?", a: "Most patients feel significant relief immediately after drainage. Complete wound healing takes 2–4 weeks." },
    ],
  },
  {
    slug: "ods",
    title: "ODS",
    altTitle: "Obstructed Defecation Syndrome",
    shortDesc: "Difficulty emptying the bowel despite the urge — specialist evaluation and treatment.",
    icon: "AlertCircle",
    seoTitle: "ODS Treatment in Palanpur | Dr. Parth Prajapati",
    seoDesc: "Expert ODS (Obstructed Defecation Syndrome) treatment in Palanpur. Dr. Parth Prajapati offers comprehensive evaluation and management.",
    heroHeadline: "ODS Treatment in Palanpur",
    definition: "Obstructed Defecation Syndrome (ODS) is a condition where patients experience difficulty emptying the bowel despite having the urge to defecate. It accounts for a significant portion of chronic constipation cases. ODS can result from structural problems (rectocele, intussusception) or functional issues (pelvic floor dyssynergia). A thorough evaluation is essential for effective treatment.",
    causes: [
      { label: "Rectocele", desc: "A bulging of the front wall of the rectum into the vagina, trapping stool" },
      { label: "Rectal Intussusception", desc: "Internal telescoping of the rectal wall that blocks the passage" },
      { label: "Pelvic Floor Dyssynergia", desc: "Uncoordinated pelvic floor muscles that fail to relax during defecation" },
      { label: "Enterocele", desc: "Small bowel hernia pushing into the rectovaginal space" },
      { label: "Excessive Perineal Descent", desc: "Abnormal lowering of the pelvic floor during straining" },
      { label: "Mucosal Prolapse", desc: "Internal prolapse of the rectal lining blocking the outlet" },
    ],
    symptoms: [
      { label: "Straining", desc: "Excessive and prolonged straining during bowel movements" },
      { label: "Incomplete Evacuation", desc: "Persistent feeling of not fully emptying despite repeated attempts" },
      { label: "Digital Assistance", desc: "Need to manually assist bowel movements with finger pressure" },
      { label: "Bloating", desc: "Abdominal bloating and discomfort from retained stool" },
      { label: "Frequent Toilet Visits", desc: "Multiple trips to the toilet with minimal result" },
    ],
    conservative: [
      "Biofeedback therapy for pelvic floor retraining",
      "High-fiber diet with adequate fluid intake",
      "Bowel habit training and scheduled toilet time",
      "Pelvic floor physiotherapy",
      "Laxatives and stool softeners as needed",
      "Behavioral modifications and stress management",
    ],
    surgical: [
      { procedure: "STARR Procedure", desc: "Stapled transanal rectal resection for internal prolapse and rectocele", advantages: "Addresses structural cause, good long-term outcomes", disadvantages: "Risk of urgency, bleeding, requires careful patient selection" },
      { procedure: "Laparoscopic Ventral Rectopexy", desc: "Mesh-based rectal suspension via keyhole surgery", advantages: "Minimally invasive, addresses prolapse and rectocele", disadvantages: "Mesh-related complications possible, longer procedure" },
      { procedure: "Rectocele Repair", desc: "Surgical correction of the rectocele bulge", advantages: "Directly addresses the anatomical defect", disadvantages: "Recurrence possible, may need additional procedures" },
    ],
    aftercare: [
      "Continue biofeedback therapy post-operatively",
      "Maintain a high-fiber diet and adequate hydration",
      "Avoid straining — use stool softeners as needed",
      "Pelvic floor exercises as recommended",
      "Regular follow-up for functional assessment",
      "Report any changes in bowel habits promptly",
    ],
    faqs: [
      { q: "What is ODS?", a: "Obstructed Defecation Syndrome is difficulty emptying the bowel despite the urge, caused by structural or functional problems in the pelvic floor." },
      { q: "How is ODS diagnosed?", a: "Diagnosis involves clinical examination, defecography (dynamic imaging), anal manometry, and sometimes MRI to identify the specific cause." },
      { q: "Is ODS the same as constipation?", a: "ODS is a specific type of constipation (outlet constipation) where the problem is with evacuating stool, not with stool transit through the colon." },
      { q: "Can ODS be treated without surgery?", a: "Yes, many cases respond well to biofeedback therapy, dietary changes, and pelvic floor exercises. Surgery is reserved for structural causes." },
      { q: "What is biofeedback therapy?", a: "Biofeedback is a specialized therapy that teaches patients to coordinate their pelvic floor muscles correctly during bowel movements." },
    ],
  },
  {
    slug: "constipation",
    title: "Constipation",
    altTitle: "Chronic Constipation",
    shortDesc: "Persistent difficulty passing stools — comprehensive evaluation and management.",
    icon: "Clock",
    seoTitle: "Constipation Treatment in Palanpur | Dr. Parth Prajapati",
    seoDesc: "Expert constipation management in Palanpur by Dr. Parth Prajapati. Comprehensive evaluation and treatment for chronic constipation.",
    heroHeadline: "Constipation Treatment in Palanpur",
    definition: "Chronic constipation is a common digestive condition characterized by infrequent bowel movements (fewer than three per week), hard or lumpy stools, straining, and a feeling of incomplete evacuation. While occasional constipation is normal, chronic constipation can significantly impact quality of life and may indicate underlying conditions that require specialist evaluation.",
    causes: [
      { label: "Low-Fiber Diet", desc: "Insufficient dietary fiber leads to harder, smaller stools" },
      { label: "Dehydration", desc: "Inadequate fluid intake results in dry, difficult-to-pass stools" },
      { label: "Sedentary Lifestyle", desc: "Lack of physical activity slows down bowel motility" },
      { label: "Medications", desc: "Pain medications, antidepressants, and iron supplements can cause constipation" },
      { label: "Ignoring Urge", desc: "Repeatedly ignoring the urge to defecate weakens the reflex" },
      { label: "Metabolic Disorders", desc: "Thyroid disorders, diabetes, and hormonal imbalances affect bowel function" },
      { label: "Pelvic Floor Dysfunction", desc: "Uncoordinated pelvic floor muscles impair the evacuation process" },
    ],
    symptoms: [
      { label: "Infrequent Stools", desc: "Fewer than three bowel movements per week" },
      { label: "Hard Stools", desc: "Stools that are hard, dry, or lumpy and difficult to pass" },
      { label: "Straining", desc: "Excessive effort required during bowel movements" },
      { label: "Bloating", desc: "Abdominal distension, bloating, and discomfort" },
      { label: "Incomplete Evacuation", desc: "Feeling that the bowel has not been fully emptied" },
      { label: "Abdominal Pain", desc: "Cramping or generalized abdominal pain" },
    ],
    conservative: [
      "Increase dietary fiber intake (25–35 grams per day)",
      "Drink adequate water (8–10 glasses daily)",
      "Regular physical exercise (30 minutes daily)",
      "Establish a regular bowel routine",
      "Over-the-counter stool softeners and osmotic laxatives",
      "Probiotics for gut health improvement",
    ],
    surgical: [
      { procedure: "Colonic Transit Study", desc: "Diagnostic evaluation to determine the type and severity of constipation", advantages: "Guides appropriate treatment selection", disadvantages: "Requires swallowing markers over several days" },
      { procedure: "Biofeedback Therapy", desc: "Non-surgical retraining of pelvic floor muscles for dyssynergic defecation", advantages: "Non-invasive, high success rate (70–80%), no side effects", disadvantages: "Requires multiple sessions, patient commitment needed" },
      { procedure: "Sacral Nerve Stimulation", desc: "Electrical stimulation of sacral nerves to improve bowel function", advantages: "Effective for refractory cases, reversible", disadvantages: "Invasive procedure, device maintenance required" },
    ],
    aftercare: [
      "Continue high-fiber diet and adequate hydration long-term",
      "Maintain regular physical activity",
      "Follow prescribed medication schedule",
      "Keep a bowel diary to track progress",
      "Attend follow-up appointments for ongoing management",
      "Report any worsening symptoms promptly",
    ],
    faqs: [
      { q: "When is constipation considered chronic?", a: "Constipation is considered chronic when symptoms persist for three months or longer, with fewer than three bowel movements per week." },
      { q: "Is chronic constipation serious?", a: "While not usually dangerous, chronic constipation can lead to complications like hemorrhoids, fissures, fecal impaction, and rectal prolapse if untreated." },
      { q: "What tests are done for constipation?", a: "Tests may include blood work, colonoscopy, colonic transit study, defecography, and anorectal manometry depending on the suspected cause." },
      { q: "Can constipation cause other anorectal problems?", a: "Yes. Chronic straining from constipation is a major risk factor for developing piles, fissures, and rectal prolapse." },
      { q: "Are laxatives safe for long-term use?", a: "Osmotic laxatives and fiber supplements are generally safe for long-term use. Stimulant laxatives should be used sparingly under medical guidance." },
    ],
  },
];

export const facilities = [
  { slug: "radiology", title: "Radiology", icon: "ScanLine", shortDesc: "Advanced diagnostic imaging services for accurate diagnosis and treatment planning." },
  { slug: "anal-manometry", title: "Anal Manometry", icon: "Activity", shortDesc: "Specialized pressure testing to evaluate anorectal muscle function and coordination." },
  { slug: "biofeedback-therapy", title: "Biofeedback Therapy", icon: "BrainCircuit", shortDesc: "Non-invasive pelvic floor retraining therapy for functional bowel disorders." },
  { slug: "colonoscopy", title: "Colonoscopy", icon: "Search", shortDesc: "Comprehensive endoscopic examination of the colon for screening and diagnosis." },
  { slug: "endoscopy", title: "Endoscopy", icon: "Eye", shortDesc: "Advanced visualization of the digestive tract for diagnostic and therapeutic purposes." },
  { slug: "pharmacy", title: "Pharmacy", icon: "Pill", shortDesc: "In-house pharmacy for convenient access to prescribed medications and supplies." },
  { slug: "laboratory", title: "Laboratory", icon: "FlaskConical", shortDesc: "On-site diagnostic laboratory for quick and accurate test results." },
  { slug: "health-insurance", title: "Health Insurance", icon: "ShieldCheck", shortDesc: "Cashless treatment available with all major health insurance providers." },
  { slug: "medical-tourism", title: "Medical Tourism", icon: "Plane", shortDesc: "Comprehensive care packages for out-of-town and international patients." },
  { slug: "nutrition-ayurveda", title: "Nutrition & Ayurveda", icon: "Leaf", shortDesc: "Integrative nutritional counseling and Ayurvedic therapies for holistic healing." },
];
